export const DEMO_DATE = '2026-08-09';

export const INTELLIGENCE_CONFIG = {
  ATTENDANCE_RISK_THRESHOLD: 75,
  ATTENDANCE_CRITICAL_THRESHOLD: 60,
  ATTENDANCE_TARGET_PERCENTAGE: 91.8,
  HOMEWORK_RISK_THRESHOLD: 60,
  HOMEWORK_TARGET_THRESHOLD: 75,
  TEACHER_TARGET_THRESHOLD: 75,
  RECOVERY_ESCALATION_DAYS: 90,
  RECOVERY_HIGH_VALUE_THRESHOLD: 15000,
  FEE_CREDIT_HIGH_RELIABILITY_THRESHOLD: 80,
  FEE_CREDIT_MODERATE_RELIABILITY_THRESHOLD: 65,
} as const;
